matrix:
  include:
  - name: Python 3.6
    python: 3.6
    os: linux
  - name: Python 3.7
    python: 3.7
    os: linux
  - name: Python 3.8
    python: 3.8
    os: linux
  # Cannot natively install python in Mac OS, but comes bundled with xcode so
  # using a specific xcode version can satisfy python version requirements, see:
  # https://docs.travis-ci.com/user/languages/python/
  - name: Python 3.6
    os: osx
    language: shell
    osx_image: "xcode9.4"  # Comes with v3.6.5
  - name: Python 3.7
    os: osx
    language: shell
    osx_image: "xcode10.2"  # Comes with v3.7.3
  - name: Python 3.8
    os: osx
    language: shell
    osx_image: "xcode11.5"  # Comes with v???
env:
  global:
    LIBGIT2: "~/libgit2/_install/"
    LD_LIBRARY_PATH: "${LIBGIT2}/lib:${LD_LIBRARY_PATH}"
    LIBGIT2_VERSION: "1.0.1"  # TODO Add in support for building against v0.28
before_install:
- python3 --version
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake; fi
- ./.travis.sh "${LIBGIT2_VERSION}"
install:
- echo "Install starting"
- pip3 install ".[dev]"
- echo "Install ending"
script:
- echo "Script starting"
- flake8 --config flake8.cfg battenberg
- pytest --cov=battenberg
- codecov
- echo "Script ending"
deploy:
  provider: pypi
  user: __token__
  password:
    # This is an encrypted copy of the PyPI API token which you get from your PyPI Account Settings page.
    # Generated using: travis encrypt <pypi api token> --add deploy.password
    secure: s3uaLdkOrPATnDuxGnkjIQEDsKpB42ujA2N+BLDxZmhDGsH4Cr+SwxXgdDU7Ud5UKWwKRJtAugdqzZ5ntsGmdhHzyCUUajHyI45Bg/w3iUGawu6pXT3/MEeIjG14B63J66zc0UAWmMmUxDNLE1wThVsmOL8TsgKDOV9LADvD+ryxo3owBiwYHBR9jMQtJwR9/syhSn5SiSjdBAcdxhxYYoD5tjtmfnJy+pEBrLrNXO77kfQNe5eQsK4mZ0o10NKDafkUaxd2ajuxEMcu8nlfQkZ7wA3MKW4JU/Mwe8Y2RIWVyP5vOXD2WfXS4Vze08fp+/AtwDDyj7/bLxJy2y6efWJRtg6nqqo22TfeYGP3MdztTEREKgwJUeTtOlhXPb6RSlg/0mcJcBbhAQdoEI2QUKkox64sFjld8pyNPOQr1PmAmaHWKqYpy93AEHntLQYpXFNrcmznknG6amc/+1H6rVCnfK48LMv7pTYcfuuQ8WXr56br88aoFwoIfTYAw+rSd4tbqft6rIu8DySyv/k9uIQUdx9MxFx98tiJem3UeeSWP4101iiiYcsXQh6ANSzD2JcV2jwbm2cEh+puUenEjsU5DkKbkFfh3nHOjqQd2tm/ScQuiZWYsI/q4YvR/HSNlX7r9+3R/6XeV49gTKcjQsFO1pIb/jGzPY2RHR+xnAA=
  on:
    tags: true
  skip_existing: true
