os: linux
dist: xenial
jobs:
  include:
  - name: "Python 3.6 on Linux"
    os: linux
    env: &py36
      PYTHON_VERSION: "3.6.10"
  - name: "Python 3.7 on Linux"
    os: linux
    env: &py37
      PYTHON_VERSION: "3.7.7"
  - name: "Python 3.8 on Linux"
    os: linux
    env: &py38
      PYTHON_VERSION: "3.8.3"
  # Cannot natively install python in Mac OS, but comes bundled with xcode so
  # using a specific xcode version can satisfy python version requirements, see:
  # https://docs.travis-ci.com/user/languages/python/
  - name: "Python 3.6 on Mac OS X 10.13"
    os: osx
    osx_image: "xcode9.4"  # High Sierra 10.13
    env:
      <<: *py36
  - name: "Python 3.7 on Mac OS X 10.14"
    os: osx
    osx_image: "xcode10.2"  # Mojave 10.14
    env:
      <<: *py37
  - name: "Python 3.8 on Mac OS X 10.15"
    os: osx
    osx_image: "xcode11.4"  # Catalina 10.15
    env:
      <<: *py38
env:
  global:
    LIBGIT2: "~/libgit2/_install/"
    LD_LIBRARY_PATH: "${LIBGIT2}/lib:${LD_LIBRARY_PATH}"
    LIBGIT2_VERSION: "1.0.1"  # TODO Add in support for building against v0.28
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew upgrade pyenv; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo rm -rf /opt/pyenv && curl https://pyenv.run | bash && exec $SHELL; fi
- pyenv install --list
- pyenv versions
- pyenv install $PYTHON_VERSION && pyenv global $PYTHON_VERSION
- python3 --version
- which python3
- which pip3
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake; fi
- ./.travis.sh "${LIBGIT2_VERSION}"
install:
- echo "Install starting"
- pip3 install ".[dev]"
- echo "Install ending"
script:
- echo "Script starting"
- flake8 --config flake8.cfg battenberg
- pytest --cov=battenberg
- codecov
- echo "Script ending"
deploy:
  provider: pypi
  username: __token__
  password:
    # This is an encrypted copy of the PyPI API token which you get from your PyPI Account Settings page.
    # Generated using: travis encrypt <pypi api token> --add deploy.password
    secure: s3uaLdkOrPATnDuxGnkjIQEDsKpB42ujA2N+BLDxZmhDGsH4Cr+SwxXgdDU7Ud5UKWwKRJtAugdqzZ5ntsGmdhHzyCUUajHyI45Bg/w3iUGawu6pXT3/MEeIjG14B63J66zc0UAWmMmUxDNLE1wThVsmOL8TsgKDOV9LADvD+ryxo3owBiwYHBR9jMQtJwR9/syhSn5SiSjdBAcdxhxYYoD5tjtmfnJy+pEBrLrNXO77kfQNe5eQsK4mZ0o10NKDafkUaxd2ajuxEMcu8nlfQkZ7wA3MKW4JU/Mwe8Y2RIWVyP5vOXD2WfXS4Vze08fp+/AtwDDyj7/bLxJy2y6efWJRtg6nqqo22TfeYGP3MdztTEREKgwJUeTtOlhXPb6RSlg/0mcJcBbhAQdoEI2QUKkox64sFjld8pyNPOQr1PmAmaHWKqYpy93AEHntLQYpXFNrcmznknG6amc/+1H6rVCnfK48LMv7pTYcfuuQ8WXr56br88aoFwoIfTYAw+rSd4tbqft6rIu8DySyv/k9uIQUdx9MxFx98tiJem3UeeSWP4101iiiYcsXQh6ANSzD2JcV2jwbm2cEh+puUenEjsU5DkKbkFfh3nHOjqQd2tm/ScQuiZWYsI/q4YvR/HSNlX7r9+3R/6XeV49gTKcjQsFO1pIb/jGzPY2RHR+xnAA=
  on:
    tags: true
  skip_existing: true
